name: paw_pick
description: Mobile app for Pet shelters and Pet lovers
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.15
  introduction_screen: ^3.0.3
  carousel_slider: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
flutter:
  uses-material-design: true
  assets:
    - 'assets/dog2.png'
    - 'assets/dog3.png'
    - 'assets/dog1.png'
    - 'assets/btn_back.png'
    - assets/filters_pics/cat_icon_white.png
    - assets/filters_pics/cat_icon_yellow.png
    - assets/filters_pics/dog_icon_white.png
    - assets/filters_pics/dog_icon_yellow.png

    - assets/filters_pics/male_icon_white.png
    - assets/filters_pics/male_icon_yellow.png
    - assets/filters_pics/female_icon_white.png
    - assets/filters_pics/female_icon_yellow.png

    - assets/filters_pics/calm_icon_white.png
    - assets/filters_pics/calm_icon_yellow.png
    - assets/filters_pics/active_icon_white.png
    - assets/filters_pics/active_icon_yellow.png

    - assets/filters_pics/small_icon_white.png
    - assets/filters_pics/small_icon_yellow.png
    - assets/filters_pics/medium_icon_white.png
    - assets/filters_pics/medium_icon_yellow.png
    - assets/filters_pics/large_icon_white.png
    - assets/filters_pics/large_icon_yellow.png

    - assets/filters_pics/young_icon_white.png
    - assets/filters_pics/young_icon_black.png
    - assets/filters_pics/adult_icon_white.png
    - assets/filters_pics/adult_icon_black.png
    - assets/filters_pics/old_icon_white.png
    - assets/filters_pics/old_icon_black.png
    - assets/filters_pics/filters_next/short_icon_white.png
    - assets/filters_pics/filters_next/short_icon_yellow.png
    - assets/filters_pics/filters_next/long_icon_white.png
    - assets/filters_pics/filters_next/long_icon_yellow.png

    - assets/form/home_for_pets.png

    - assets/ai_pics/robot_2.png
    - assets/ai_pics/pet_1.png
    - assets/ai_pics/dog_2.png
    - assets/ai_pics/arrow-right.png

    - assets/profile/photo.png

    - assets/menu/cards.png
    - assets/menu/favs.png
    - assets/menu/profile.png

    - assets/menu/cards_active.png
    - assets/menu/favs_active.png
    - assets/menu/profile_active.png
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
